import {
  app,
  BrowserWindow,
  dialog,
  ipcMain,
  screen,
  type NativeImage,
} from "electron";
import { randomBytes } from "node:crypto";
import { unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

export type PrintHtmlOptions = {
  landscape?: boolean;
};

export type SavePdfResult =
  | { cancelled: true }
  | { ok: true; path: string };

const HEADER_TEMPLATE = `<div style="width:100%;height:100%;margin:0;padding:0;background:#ffffff;font-size:0;"></div>`;
const FOOTER_TEMPLATE = `<div style="width:100%;height:100%;margin:0;padding:0 8mm;box-sizing:border-box;font-family:Arial,sans-serif;color:#000;background:#ffffff;-webkit-print-color-adjust:exact;print-color-adjust:exact;"><div style="border-top:1px solid #000;margin:0 0 2px;width:100%;height:0;"></div><div style="font-size:8px;font-style:italic;text-align:right;">Generated by Sales Management Application</div></div>`;

function createPdfWindow(): BrowserWindow {
  // No opacity: 0. On Windows a fully transparent window is never composited,
  // so printToPDF returns a valid file whose pages are blank.
  return new BrowserWindow({
    width: 794,
    height: 1123,
    show: false,
    backgroundColor: "#ffffff",
    paintWhenInitiallyHidden: true,
    frame: false,
    skipTaskbar: true,
    focusable: false,
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      backgroundThrottling: false,
    },
  });
}

function createPrintWindow(parent?: BrowserWindow): BrowserWindow {
  // Stays hidden. The system print dialog is owned by this window, and a
  // visible copy is only a blank page beside the dialog.
  return new BrowserWindow({
    parent,
    width: 794,
    height: 1123,
    show: false,
    frame: false,
    skipTaskbar: true,
    focusable: true,
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
  });
}

async function loadHtmlDocument(
  target: BrowserWindow,
  html: string,
): Promise<string> {
  const tempPath = join(tmpdir(), `report-${randomBytes(8).toString("hex")}.html`);
  await writeFile(tempPath, html, "utf8");

  const loadDone = new Promise<void>((resolve, reject) => {
    const timer = setTimeout(() => {
      cleanup();
      reject(new Error("Timed out loading print document"));
    }, 20000);

    const onFail = (
      _event: Electron.Event,
      errorCode: number,
      errorDescription: string,
    ) => {
      cleanup();
      reject(new Error(`Load failed (${errorCode}): ${errorDescription}`));
    };
    const onDone = () => {
      cleanup();
      resolve();
    };
    const cleanup = () => {
      clearTimeout(timer);
      target.webContents.removeListener("did-finish-load", onDone);
      target.webContents.removeListener("did-fail-load", onFail);
    };

    target.webContents.once("did-finish-load", onDone);
    target.webContents.once("did-fail-load", onFail);
  });

  await target.loadURL(pathToFileURL(tempPath).href);
  await loadDone;
  return tempPath;
}

async function waitForPrintReady(printWindow: BrowserWindow): Promise<void> {
  await printWindow.webContents.executeJavaScript(
    `(async () => {
      if (document.fonts && document.fonts.ready) await document.fonts.ready
      await new Promise((resolve) => {
        requestAnimationFrame(() => requestAnimationFrame(resolve))
      })
      return true
    })()`,
  );
}

function bitmapHasInk(image: NativeImage): boolean {
  const { width, height } = image.getSize();
  if (width === 0 || height === 0) return false;
  const bitmap = image.toBitmap();
  const stepX = Math.max(1, Math.floor(width / 24));
  const stepY = Math.max(1, Math.floor(height / 32));
  for (let y = 0; y < height; y += stepY) {
    for (let x = 0; x < width; x += stepX) {
      const offset = (y * width + x) * 4;
      const blue = bitmap[offset] ?? 255;
      const green = bitmap[offset + 1] ?? 255;
      const red = bitmap[offset + 2] ?? 255;
      if (red < 250 || green < 250 || blue < 250) return true;
    }
  }
  return false;
}

/** Hidden windows on Windows often paint white. Show one long enough to composite, behind the app. */
async function ensurePdfPainted(printWindow: BrowserWindow): Promise<void> {
  printWindow.setOpacity(1);
  printWindow.setPosition(-20000, -20000);
  printWindow.showInactive();
  await waitForPrintReady(printWindow);
  let painted = false;
  try {
    painted = bitmapHasInk(await printWindow.webContents.capturePage());
  } catch {
    painted = false;
  }
  if (painted) return;

  const area = screen.getPrimaryDisplay().workArea;
  printWindow.setBounds({
    x: area.x + 24,
    y: area.y + 24,
    width: 794,
    height: Math.min(1123, Math.max(400, area.height - 48)),
  });
  printWindow.showInactive();
  const front = BrowserWindow.getAllWindows().find(
    (other) =>
      other.id !== printWindow.id && !other.isDestroyed() && other.isVisible(),
  );
  front?.moveTop();
  await waitForPrintReady(printWindow);
}

function requestPrint(
  contents: Electron.WebContents,
  options: Electron.WebContentsPrintOptions,
): Promise<{ success: boolean; failureReason: string }> {
  return new Promise((resolve) => {
    contents.print(options, (success, failureReason) => {
      resolve({
        success,
        failureReason: typeof failureReason === "string" ? failureReason : "",
      });
    });
  });
}

function printWebContents(contents: Electron.WebContents): Promise<void> {
  return (async () => {
    // Electron 43.0–43.1 rejects every non-empty print options object with
    // "Invalid printer settings" and can leave the print job hanging if a
    // second call follows. The PDF already carries page size and backgrounds.
    const result = await requestPrint(contents, {});
    const cancelled = /cancel/i.test(result.failureReason);
    if (result.success || cancelled) return;
    throw new Error(result.failureReason || "Print failed");
  })();
}

function assertHtml(html: unknown): asserts html is string {
  if (typeof html !== "string" || html.trim().length === 0) {
    throw new Error("Print HTML is required");
  }
}

function sanitizePdfFileName(value: unknown): string {
  const raw = typeof value === "string" ? value : "report.pdf";
  const base = raw.replace(/[/\\?%*:|"<>]/g, "_").trim();
  const named = base || "report.pdf";
  return named.toLowerCase().endsWith(".pdf") ? named : `${named}.pdf`;
}

function ensurePdfExtension(path: string): string {
  return path.toLowerCase().endsWith(".pdf") ? path : `${path}.pdf`;
}

function toUint8Array(value: unknown): Uint8Array | null {
  if (value instanceof Uint8Array) return value;
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (ArrayBuffer.isView(value)) {
    return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
  }
  return null;
}

export function registerPrintHandlers(): void {
  ipcMain.handle(
    "print:htmlToPdf",
    async (_event, html: unknown, _options?: PrintHtmlOptions) => {
      assertHtml(html);
      const printWindow = createPdfWindow();
      let tempPath: string | null = null;

      try {
        tempPath = await loadHtmlDocument(printWindow, html);
        await ensurePdfPainted(printWindow);
        // A4 in microns. preferCSSPageSize lets the document @page rule win.
        // displayHeaderFooter repeats the attribution line, because printToPDF
        // drops position:fixed elements inside the page.
        const pdfBuffer = await printWindow.webContents.printToPDF({
          printBackground: true,
          landscape: false,
          pageSize: {
            width: 210000,
            height: 297000,
          },
          preferCSSPageSize: true,
          displayHeaderFooter: true,
          headerTemplate: HEADER_TEMPLATE,
          footerTemplate: FOOTER_TEMPLATE,
          margins: {
            marginType: "custom",
            top: 0.315,
            bottom: 0.55,
            left: 0.315,
            right: 0.315,
          },
        });
        if (!pdfBuffer || pdfBuffer.byteLength === 0) {
          throw new Error("PDF generation returned empty output");
        }
        return pdfBuffer.toString("base64");
      } finally {
        if (!printWindow.isDestroyed()) printWindow.destroy();
        if (tempPath) await unlink(tempPath).catch(() => undefined);
      }
    },
  );

  ipcMain.handle(
    "print:printHtml",
    async (event, html: unknown, _options?: PrintHtmlOptions) => {
      assertHtml(html);
      const parent = BrowserWindow.fromWebContents(event.sender) ?? undefined;
      const printWindow = createPrintWindow(parent);
      let tempPath: string | null = null;

      try {
        tempPath = await loadHtmlDocument(printWindow, html);
        await waitForPrintReady(printWindow);
        await printWebContents(printWindow.webContents);
        return { ok: true as const };
      } finally {
        if (!printWindow.isDestroyed()) printWindow.destroy();
        if (tempPath) await unlink(tempPath).catch(() => undefined);
      }
    },
  );

  ipcMain.handle("print:printPdf", async (event, data: unknown) => {
    const bytes = toUint8Array(data);
    if (!bytes || bytes.byteLength === 0) {
      throw new Error("PDF data is required");
    }
    const tempPath = join(tmpdir(), `report-${randomBytes(8).toString("hex")}.pdf`);
    await writeFile(tempPath, bytes);
    const parent = BrowserWindow.fromWebContents(event.sender) ?? undefined;
    const printWindow = createPrintWindow(parent);
    try {
      await printWindow.loadURL(pathToFileURL(tempPath).href);
      await waitForPrintReady(printWindow);
      await printWebContents(printWindow.webContents);
      return { ok: true as const };
    } finally {
      if (!printWindow.isDestroyed()) printWindow.destroy();
      await unlink(tempPath).catch(() => undefined);
    }
  });

  ipcMain.handle(
    "print:savePdf",
    async (
      event,
      payload: { defaultName?: unknown; data?: unknown },
    ): Promise<SavePdfResult> => {
      const defaultName = sanitizePdfFileName(payload?.defaultName);
      const data = toUint8Array(payload?.data);
      if (!data || data.byteLength === 0) {
        throw new Error("PDF data is required");
      }

      const parentWindow = BrowserWindow.fromWebContents(event.sender);
      const options = {
        title: "Save PDF",
        defaultPath: join(app.getPath("documents"), defaultName),
        filters: [{ name: "PDF", extensions: ["pdf"] }],
      };
      const result = parentWindow
        ? await dialog.showSaveDialog(parentWindow, options)
        : await dialog.showSaveDialog(options);
      if (result.canceled || !result.filePath) {
        return { cancelled: true };
      }

      const filePath = ensurePdfExtension(result.filePath);
      await writeFile(filePath, data);
      return { ok: true, path: filePath };
    },
  );
}
