import { BrowserWindow, dialog, ipcMain } from "electron";
import fs from "node:fs/promises";

export type ExportPdfResult =
  | { ok: true; filePath: string }
  | { ok: false; cancelled: true }
  | { ok: false; cancelled: false; error: string };

export function registerPrintHandlers(): void {
  ipcMain.handle(
    "print:exportPdf",
    async (event, defaultFileName?: string): Promise<ExportPdfResult> => {
      const win = BrowserWindow.fromWebContents(event.sender);
      if (!win || win.isDestroyed()) {
        return { ok: false, cancelled: false, error: "No window available for PDF export." };
      }

      const suggestedName =
        typeof defaultFileName === "string" && defaultFileName.trim().length > 0
          ? defaultFileName.trim()
          : `report-${new Date().toISOString().slice(0, 10)}.pdf`;

      const { canceled, filePath } = await dialog.showSaveDialog(win, {
        title: "Save PDF",
        defaultPath: suggestedName,
        filters: [{ name: "PDF", extensions: ["pdf"] }],
      });

      if (canceled || !filePath) {
        return { ok: false, cancelled: true };
      }

      try {
        // A4 = 210mm × 297mm. Microns keep size exact across Electron/Chromium builds.
        // displayHeaderFooter renders the attribution line/text on every PDF page because
        // Chromium printToPDF omits position:fixed elements inside the page body.
        const pdf = await win.webContents.printToPDF({
          printBackground: true,
          landscape: false,
          pageSize: {
            width: 210000,
            height: 297000,
          },
          preferCSSPageSize: true,
          displayHeaderFooter: true,
          headerTemplate: "<div></div>",
          footerTemplate: `<div style="width:100%;margin:0;padding:0 8mm;box-sizing:border-box;font-family:Arial,sans-serif;color:#000;"><div style="border-top:1px solid #000;margin:0 0 2px;width:100%;height:0;"></div><div style="font-size:8px;font-style:italic;text-align:right;">Generated by Sales Management Application</div></div>`,
          margins: {
            marginType: "custom",
            top: 0.315,
            bottom: 0.55,
            left: 0.315,
            right: 0.315,
          },
        });
        await fs.writeFile(filePath, pdf);
        return { ok: true, filePath };
      } catch (error) {
        return {
          ok: false,
          cancelled: false,
          error: error instanceof Error ? error.message : "Failed to export PDF.",
        };
      }
    },
  );
}
