import { getDatabase } from "../db/index.js";

export function loadAutoGenerateSalesInvoiceNo(): boolean {
  try {
    const db = getDatabase();
    const columns = db
      .prepare(`PRAGMA table_info(CompanySettings)`)
      .all() as Array<{ name: string }>;
    if (!columns.some((col) => col.name === "autoGenerateSalesInvoiceNo")) {
      return false;
    }

    const row = db
      .prepare(
        `SELECT autoGenerateSalesInvoiceNo
         FROM CompanySettings
         WHERE id = 'default'`,
      )
      .get() as { autoGenerateSalesInvoiceNo: number | null } | undefined;

    return Number(row?.autoGenerateSalesInvoiceNo ?? 0) !== 0;
  } catch {
    return false;
  }
}

export function loadAutoGenerateDeliveryOrderNo(): boolean {
  try {
    const db = getDatabase();
    const columns = db
      .prepare(`PRAGMA table_info(CompanySettings)`)
      .all() as Array<{ name: string }>;
    if (!columns.some((col) => col.name === "autoGenerateDeliveryOrderNo")) {
      return false;
    }

    const row = db
      .prepare(
        `SELECT autoGenerateDeliveryOrderNo
         FROM CompanySettings
         WHERE id = 'default'`,
      )
      .get() as { autoGenerateDeliveryOrderNo: number | null } | undefined;

    return Number(row?.autoGenerateDeliveryOrderNo ?? 0) !== 0;
  } catch {
    return false;
  }
}

export function loadEnforceSalesInvoiceBookletValidation(): boolean {
  try {
    const db = getDatabase();
    const columns = db
      .prepare(`PRAGMA table_info(CompanySettings)`)
      .all() as Array<{ name: string }>;
    if (!columns.some((col) => col.name === "enforceSalesInvoiceBookletValidation")) {
      return false;
    }

    const row = db
      .prepare(
        `SELECT enforceSalesInvoiceBookletValidation
         FROM CompanySettings
         WHERE id = 'default'`,
      )
      .get() as { enforceSalesInvoiceBookletValidation: number | null } | undefined;

    return Number(row?.enforceSalesInvoiceBookletValidation ?? 0) !== 0;
  } catch {
    return false;
  }
}

export function loadEnforceDeliveryOrderBookletValidation(): boolean {
  try {
    const db = getDatabase();
    const columns = db
      .prepare(`PRAGMA table_info(CompanySettings)`)
      .all() as Array<{ name: string }>;
    if (!columns.some((col) => col.name === "enforceDeliveryOrderBookletValidation")) {
      return false;
    }

    const row = db
      .prepare(
        `SELECT enforceDeliveryOrderBookletValidation
         FROM CompanySettings
         WHERE id = 'default'`,
      )
      .get() as { enforceDeliveryOrderBookletValidation: number | null } | undefined;

    return Number(row?.enforceDeliveryOrderBookletValidation ?? 0) !== 0;
  } catch {
    return false;
  }
}
