import "./ReportAttributionFooter.css";

export function ReportAttributionFooter() {
  return (
    <footer class="report-attribution-footer" aria-label="Document attribution">
      <div class="report-attribution-footer-line" role="presentation" />
      <p class="report-attribution-footer-text">
        Generated by Sales Management Application
      </p>
    </footer>
  );
}
