import type { BottleOilStockSalesReport, BottledPalmOilSalesReturnReport, BottledWeeklyIssuesReport, CommitmentReport, DailySalesReport, IndustryProductMonthlySalesReport, MonthlyBottledOilReport, MonthlyDeliveriesByDestinationReport, MonthlyDeliveryReport, MonthlyPalmOilSalesReport, PalmOilSalesActivityReport, MonthlyPaymentDeliveryReport, MonthlyStockReconciliationReport, OtherProductSalesDeliveriesReport, RevenueTaxesReport, SalesBudgetMonthlyCrosstabReport, SalesBudgetMonthlyRevenueCrosstabReport, SalesBudgetWeeklyCrosstabReport, SalesBudgetWeeklyRevenueCrosstabReport, StockCommitmentReport, StockReport, WeeklyDeliveriesReport } from "../../shared/reports.types.ts";
import type { BinCardReport } from "../../shared/stock.types.ts";
export declare const HIDE_ZERO_ROWS_HINT = "Turn off Hide rows with zero or empty quantities in Report settings to see zero-balance rows.";
export declare function isStockReportEmpty(report: StockReport): boolean;
export declare function isStockCommitmentReportEmpty(report: StockCommitmentReport): boolean;
export declare function isCommitmentReportEmpty(report: CommitmentReport): boolean;
export declare function isBottleOilStockSalesReportEmpty(report: BottleOilStockSalesReport): boolean;
export declare function isWeeklyDeliveriesReportEmpty(report: WeeklyDeliveriesReport): boolean;
export declare function isDailySalesReportEmpty(report: DailySalesReport): boolean;
export declare function isMonthlyDeliveryReportEmpty(report: MonthlyDeliveryReport): boolean;
export declare function isMonthlyStockReconciliationReportEmpty(report: MonthlyStockReconciliationReport): boolean;
export declare function isMonthlyPaymentDeliveryReportEmpty(report: MonthlyPaymentDeliveryReport): boolean;
export declare function isMonthlyDeliveriesByDestinationReportEmpty(report: MonthlyDeliveriesByDestinationReport): boolean;
export declare function isMonthlyPalmOilSalesReportEmpty(report: MonthlyPalmOilSalesReport): boolean;
export declare function isPalmOilSalesActivityReportEmpty(report: PalmOilSalesActivityReport): boolean;
export declare function isIndustryProductMonthlySalesReportEmpty(report: IndustryProductMonthlySalesReport): boolean;
export declare function isBottledPalmOilSalesReturnReportEmpty(report: BottledPalmOilSalesReturnReport): boolean;
export declare function isMonthlyBottledOilReportEmpty(report: MonthlyBottledOilReport): boolean;
export declare function isOtherProductSalesDeliveriesReportEmpty(report: OtherProductSalesDeliveriesReport): boolean;
export declare function isBottledWeeklyIssuesReportEmpty(report: BottledWeeklyIssuesReport): boolean;
export declare function isRevenueTaxesReportEmpty(report: RevenueTaxesReport): boolean;
export declare function isSalesBudgetMonthlyCrosstabReportEmpty(report: SalesBudgetMonthlyCrosstabReport): boolean;
export declare function isSalesBudgetWeeklyCrosstabReportEmpty(report: SalesBudgetWeeklyCrosstabReport): boolean;
export declare function salesBudgetWeeklyCrosstabEmptyMessage(report: SalesBudgetWeeklyCrosstabReport): string | null;
export declare function salesBudgetMonthlyCrosstabEmptyMessage(report: SalesBudgetMonthlyCrosstabReport): string | null;
export declare function isSalesBudgetMonthlyRevenueCrosstabReportEmpty(report: SalesBudgetMonthlyRevenueCrosstabReport): boolean;
export declare function isSalesBudgetWeeklyRevenueCrosstabReportEmpty(report: SalesBudgetWeeklyRevenueCrosstabReport): boolean;
export declare function salesBudgetWeeklyRevenueCrosstabEmptyMessage(report: SalesBudgetWeeklyRevenueCrosstabReport): string | null;
export declare function salesBudgetMonthlyRevenueCrosstabEmptyMessage(report: SalesBudgetMonthlyRevenueCrosstabReport): string | null;
export declare function isBinCardReportMovementsEmpty(report: BinCardReport): boolean;
