-- Seed stock draft/post action flags for roles that already validate stock documents.
-- Safe to re-run; INSERT OR IGNORE.

INSERT OR IGNORE INTO RoleActionPermission (role, actionKey, allowed) VALUES
  ('ADMIN', 'draft_stock_receipts', 1),
  ('ADMIN', 'post_stock_receipts', 1),
  ('ADMIN', 'draft_stock_transfers', 1),
  ('ADMIN', 'post_stock_transfers', 1),
  ('ADMIN', 'draft_stock_adjustments', 1),
  ('ADMIN', 'post_stock_adjustments', 1),
  ('MANAGER', 'draft_stock_receipts', 1),
  ('MANAGER', 'post_stock_receipts', 1),
  ('MANAGER', 'draft_stock_transfers', 1),
  ('MANAGER', 'post_stock_transfers', 1),
  ('MANAGER', 'draft_stock_adjustments', 1),
  ('MANAGER', 'post_stock_adjustments', 1),
  ('SENIOR_SALES_SUPERVISOR', 'draft_stock_receipts', 1),
  ('SENIOR_SALES_SUPERVISOR', 'post_stock_receipts', 1),
  ('SENIOR_SALES_SUPERVISOR', 'draft_stock_transfers', 1),
  ('SENIOR_SALES_SUPERVISOR', 'post_stock_transfers', 1),
  ('SENIOR_SALES_SUPERVISOR', 'draft_stock_adjustments', 1),
  ('SENIOR_SALES_SUPERVISOR', 'post_stock_adjustments', 1),
  ('STATISTICS_SUPERVISOR', 'draft_stock_receipts', 0),
  ('STATISTICS_SUPERVISOR', 'post_stock_receipts', 0),
  ('STATISTICS_SUPERVISOR', 'draft_stock_transfers', 0),
  ('STATISTICS_SUPERVISOR', 'post_stock_transfers', 0),
  ('STATISTICS_SUPERVISOR', 'draft_stock_adjustments', 0),
  ('STATISTICS_SUPERVISOR', 'post_stock_adjustments', 0),
  ('SALES_CLERK', 'draft_stock_receipts', 0),
  ('SALES_CLERK', 'post_stock_receipts', 0),
  ('SALES_CLERK', 'draft_stock_transfers', 0),
  ('SALES_CLERK', 'post_stock_transfers', 0),
  ('SALES_CLERK', 'draft_stock_adjustments', 0),
  ('SALES_CLERK', 'post_stock_adjustments', 0);
