-- Sales invoice / delivery order number mode: 1 = auto-generate, 0 = manual booklet entry (default).

ALTER TABLE CompanySettings ADD COLUMN autoGenerateSalesInvoiceNo INTEGER NOT NULL DEFAULT 0;
ALTER TABLE CompanySettings ADD COLUMN autoGenerateDeliveryOrderNo INTEGER NOT NULL DEFAULT 0;
